### ISSUE TITLE
Could you please provide more information about those items?

### ISSUE THREAD

**Issue by IMoonKeyBoy** [flamewei123/DEPN#6]
`CONFIG_NAME = 'bert_config.json'` and `'WEIGHTS_NAME = 'pytorch_model.bin'`

Currently this code is inconsistent in many places, especially the names of some parameters, and I hope the authors could check it further.

**Comment by flamewei123** [comment]
Thank you for reaching out and highlighting this issue. Our code is adapted from Hunter-DDM/knowledge-neurons, and the script src/custom_bert.py is designed to refactor the BERT model's forward and backward function. The problem you are encountering might be due to recent updates to the Hugging Face model hub, which now defaults to the new model format `.safetensors` instead of the previous `.bin`.

The src/custom_bert.py script is set up to read from 'bert_config.json' and 'pytorch_model.bin'. To resolve this issue, please try downloading the older format files from Hugging Face's model hub and see if they work as expected. This should help you load the necessary configurations and weights correctly.
